# Generated by Django 3.2.4 on 2026-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='توکن بازیابی رمز'),
        ),
    ]
