# Generated by Django 4.2.7 on 2026-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'کاربر عادی'), ('moderator', 'ناظر'), ('admin', 'مدیر'), ('super_admin', 'مدیر اصلی')], default='user', max_length=20, verbose_name='نقش'),
        ),
    ]
