# Generated by Django 4.2.7 on 2026-08-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_code_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='style_preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='ترجیحات سبک پوشاک'),
        ),
    ]
