# Generated by Django 4.2.30 on 2026-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_support_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_last_seen',
            field=models.BooleanField(default=False, verbose_name='مخفی کردن آخرین بازدید'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بازدید'),
        ),
    ]
