# Generated by Django 4.2.7 on 2026-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=20, verbose_name='تلفن ۱')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='تلفن ۲')),
                ('email1', models.EmailField(max_length=254, verbose_name='ایمیل ۱')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل ۲')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('working_hours', models.CharField(max_length=200, verbose_name='ساعات کاری')),
                ('working_hours_closed', models.CharField(blank=True, max_length=100, verbose_name='روزهای تعطیل')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.URLField(verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'آیتم کتاب استایل',
                'verbose_name_plural': 'آیتم\u200cهای کتاب استایل',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='استایل خود را کشف کنید', max_length=200, verbose_name='عنوان اصلی')),
                ('hero_subtitle', models.CharField(default='مد و فشن با کیفیت برای مردان، زنان و کودکان', max_length=400, verbose_name='زیرعنوان')),
                ('hero_image', models.URLField(blank=True, verbose_name='تصویر هدر')),
                ('about_title', models.CharField(default='درباره ما', max_length=200, verbose_name='عنوان درباره ما')),
                ('about_content', models.TextField(blank=True, verbose_name='محتوای درباره ما')),
                ('about_image', models.URLField(blank=True, verbose_name='تصویر درباره ما')),
                ('shipping_title', models.CharField(default='ارسال و تحویل', max_length=200, verbose_name='عنوان ارسال')),
                ('shipping_content', models.TextField(blank=True, verbose_name='محتوای ارسال')),
                ('returns_title', models.CharField(default='بازگشت کالا', max_length=200, verbose_name='عنوان بازگشت')),
                ('returns_content', models.TextField(blank=True, verbose_name='محتوای بازگشت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
