# Generated by Django 4.2.7 on 2026-07-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbookitem',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='آدرس تصویر (جایگزین)'),
        ),
        migrations.AlterField(
            model_name='lookbookitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lookbook/', verbose_name='تصویر'),
        ),
    ]
