# Generated by Django 4.2.7 on 2026-07-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_lookbookitem_image_url_alter_lookbookitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('role', models.CharField(blank=True, default='خریدار', max_length=100, verbose_name='سمت')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='امتیاز')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['-is_approved', '-created_at'],
            },
        ),
    ]
