# Generated by Django 4.2.7 on 2026-07-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_testimonial_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('icon', models.CharField(choices=[('Truck', 'ارسال'), ('Shield', 'ضمانت'), ('RotateCcw', 'بازگشت'), ('Headphones', 'پشتیبانی'), ('Star', 'ستاره'), ('Heart', 'علاقه'), ('Clock', 'زمان'), ('CheckCircle', 'تایید')], default='Truck', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='text-blue-500', max_length=50, verbose_name='رنگ آیکون')),
                ('bg_color', models.CharField(default='bg-blue-500/10', max_length=50, verbose_name='رنگ پس\u200cزمینه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی سایت',
                'verbose_name_plural': 'ویژگی\u200cهای سایت',
                'ordering': ['order'],
            },
        ),
    ]
