# Generated by Django 4.2.7 on 2026-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=0, default=500000, help_text='سفارش\u200cهای بالاتر یا مساوی این مبلغ، ارسال رایگان می\u200cگیرند. مثال: ۵۰۰۰۰۰', max_digits=12, verbose_name='آستانه ارسال رایگان (تومان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=45000, help_text='هزینه ارسال وقتی سفارش به آستانه ارسال رایگان نرسیده باشد.', max_digits=12, verbose_name='هزینه ارسال (تومان)'),
        ),
    ]
