# Generated by Django 4.2.7 on 2026-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_site_shipping_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True, default='#', verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='site_description',
            field=models.TextField(blank=True, default='مقصد شما برای کشف جدیدترین مد\u200cها و استایل\u200cهای روز دنیا.', verbose_name='توضیحات سایت'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='site_name',
            field=models.CharField(default='فروشگاه مد', max_length=200, verbose_name='نام سایت'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='telegram_url',
            field=models.URLField(blank=True, default='#', verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter_url',
            field=models.URLField(blank=True, default='#', verbose_name='لینک توییتر'),
        ),
    ]
