# Generated by Django 3.2.4 on 2026-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contactinfo_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.09, help_text='مثلاً 0.09 для ۹٪', max_digits=4, verbose_name='نرخ مالیات'),
        ),
    ]
