# Generated by Django 4.2.7 on 2026-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitesettings_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=98, verbose_name='درصد رضایت')),
                ('title', models.CharField(default='رضایت مشتریان', max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='بر اساس نظرات و امتیازات ثبت شده توسط مشتریان', verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'رضایت مشتری',
                'verbose_name_plural': 'رضایت مشتریان',
            },
        ),
    ]
