# Generated by Django 4.2.7 on 2026-07-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_customersatisfaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LookbookItem',
        ),
    ]
