# Generated by Django 4.2.7 on 2026-07-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری پرداخت'),
        ),
    ]
