# Generated by Django 4.2.7 on 2026-07-29 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_order_postal_tracking_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخفیف')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداقل مبلغ سفارش')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='اعتبار از')),
                ('valid_until', models.DateTimeField(verbose_name='اعتبار تا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.coupon', verbose_name='کوپن')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کوپن',
                'verbose_name_plural': 'استفاده\u200cهای کوپن',
                'ordering': ['-used_at'],
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
