# Generated by Django 4.2.7 on 2026-07-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_coupon_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضای رزرو'),
        ),
    ]
