# Generated by Django 4.2.7 on 2026-07-29 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_order_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_welcome_offer',
            field=models.BooleanField(default=False, verbose_name='هدیه خوش\u200cآمدگویی'),
        ),
        migrations.CreateModel(
            name='WelcomeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_claims', to='orders.coupon', verbose_name='کوپن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_claims', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دریافت هدیه خوش\u200cآمدگویی',
                'verbose_name_plural': 'دریافت\u200cهای هدیه خوش\u200cآمدگویی',
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
