# Generated by Django 4.2.7 on 2026-07-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_coupon_is_welcome_offer_welcomeclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('pending', 'در انتظار بررسی'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده'), ('returned', 'مرجوع شده')], default='pending_payment', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
