# Generated by Django 4.2.7 on 2026-08-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_guest_email_order_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='کوپن استفاده\u200cشده'),
        ),
    ]
