# Generated by Django 5.2.17 on 2026-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_inventory_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('pending', 'در انتظار بررسی'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده'), ('paid_inventory_issue', 'پرداخت شده — نیازمند بررسی موجودی'), ('returned', 'مرجوع شده')], default='pending_payment', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
