# Generated by Django 5.2.17 on 2026-08-14

from django.db import migrations, models
from django.db.models import F


def backfill_unambiguous_product_sources(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    OrderItem.objects.filter(
        order__inventory_reserved_at__isnull=False,
        variant__isnull=True,
        inventory_source__isnull=True,
    ).update(
        inventory_source='PRODUCT',
        inventory_reserved_quantity=F('quantity'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_order_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory_reserved_quantity',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory_source',
            field=models.CharField(
                blank=True,
                choices=[('PRODUCT', 'Product inventory'), ('VARIANT', 'Variant inventory')],
                editable=False,
                max_length=7,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_unambiguous_product_sources,
            migrations.RunPython.noop,
        ),
    ]
