# Generated by Django 4.2.30 on 2026-08-06 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def accept_existing_conversations(apps, schema_editor):
    """گفتگوهایی که از قبل پیام دارند به‌صورت خودکار تایید شده در نظر گرفته می‌شوند
    تا کاربران فعلی از دسترسی به گفتگوهای موجود محروم نشوند."""
    Conversation = apps.get_model('chat', 'Conversation')
    Conversation.objects.filter(messages__isnull=False).distinct().update(status='accepted')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('declined', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.RunPython(accept_existing_conversations, migrations.RunPython.noop),
    ]
