# Generated by Django 4.2.30 on 2026-08-07 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_conversation_requested_by_conversation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_received', to=settings.AUTH_USER_MODEL, verbose_name='بلاک\u200cشده')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_made', to=settings.AUTH_USER_MODEL, verbose_name='بلاک\u200cکننده')),
            ],
            options={
                'verbose_name': 'بلاک',
                'verbose_name_plural': 'بلاک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_pair'),
        ),
    ]
