# Generated by Django 4.2.30 on 2026-08-07 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_block_block_unique_block_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, help_text='کاربرانی که این پیام را از دید خود حذف کرده\u200cاند (حذف یک\u200cطرفه).', related_name='chat_deleted_messages', to=settings.AUTH_USER_MODEL, verbose_name='حذف\u200cشده برای کاربران'),
        ),
    ]
