# Generated by Django 4.2.30 on 2026-08-14 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style_rooms', '0002_alter_styleroom_visibility'),
        ('chat', '0005_conversation_chat_conv_updated_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleRoomMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خواندن')),
            ],
            options={
                'verbose_name': 'خواندن پیام اتاق استایل',
                'verbose_name_plural': 'خواندن پیام\u200cهای اتاق استایل',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='style_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='style_rooms.styleroom', verbose_name='ناحیه استایل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='گفتگو'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['style_room', 'created_at', 'id'], name='chat_msg_room_created_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('conversation__isnull', False), ('style_room__isnull', True)), models.Q(('conversation__isnull', True), ('style_room__isnull', False)), _connector='OR'), name='chat_msg_exactly_one_context'),
        ),
        migrations.AddField(
            model_name='styleroommessageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_room_reads', to='chat.message', verbose_name='پیام'),
        ),
        migrations.AddField(
            model_name='styleroommessageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_room_message_reads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='styleroommessageread',
            index=models.Index(fields=['user', '-read_at'], name='chat_room_read_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='styleroommessageread',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='chat_room_read_message_user_unique'),
        ),
    ]
