# Generated by Django 4.2.30 on 2026-08-19 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_styleroommessageread_message_style_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chat.message', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_receipts', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'رسید پیام',
                'verbose_name_plural': 'رسیدهای پیام',
                'indexes': [models.Index(fields=['user', 'seen_at'], name='chat_receipt_user_seen_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagereceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='chat_receipt_message_user_unique'),
        ),
    ]
