# Generated by Django 4.2.30 on 2026-08-19 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_chat_receipts_and_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'هرزنامه'), ('abuse', 'محتوای نامناسب'), ('harassment', 'آزار'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دلیل')),
                ('details', models.TextField(blank=True, verbose_name='توضیح')),
                ('status', models.CharField(choices=[('open', 'باز'), ('reviewed', 'بررسی\u200cشده'), ('dismissed', 'رد شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'گزارش پیام',
                'verbose_name_plural': 'گزارش\u200cهای پیام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='آدرس پوش')),
                ('p256dh', models.CharField(max_length=200, verbose_name='کلید p256dh')),
                ('auth', models.CharField(max_length=200, verbose_name='کلید auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'اشتراک پوش',
                'verbose_name_plural': 'اشتراک\u200cهای پوش',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='حذف برای همه'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_tombstones', to=settings.AUTH_USER_MODEL, verbose_name='حذف\u200cکننده'),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='chat.message', verbose_name='هدایت\u200cشده از'),
        ),
        migrations.AddField(
            model_name='message',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='کلید تکرارنشدن'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='پاسخ به'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'idempotency_key'], name='chat_msg_conv_idem_idx'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.conversation', verbose_name='گفتگو'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.message', verbose_name='پیام'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گزارش\u200cشده'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'created_at'], name='chat_push_user_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['reporter', 'created_at'], name='chat_report_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['status', 'created_at'], name='chat_report_status_idx'),
        ),
    ]
