# Generated by Django 4.2.30 on 2026-08-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_reply_forward_report_push'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('conversation', 'sender', 'idempotency_key'), name='chat_msg_conv_sender_idem_uniq'),
        ),
    ]
