# Generated by Django 4.2.30 on 2026-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_idempotency_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('style_room', 'sender', 'idempotency_key'), name='chat_msg_room_sender_idem_uniq'),
        ),
    ]
