# Generated by Django 4.2.30 on 2026-08-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_room_idempotency_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='chat.message', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی پیام',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cهای پیام',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=20, verbose_name='ایموجی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'واکنش پیام',
                'verbose_name_plural': 'واکنش\u200cهای پیام',
                'indexes': [models.Index(fields=['message', 'created_at'], name='chat_reaction_msg_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='chat_reaction_message_user_unique'),
        ),
        migrations.AddIndex(
            model_name='messagefavorite',
            index=models.Index(fields=['user', 'created_at'], name='chat_favorite_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagefavorite',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='chat_favorite_message_user_unique'),
        ),
    ]
