# Generated by Django 4.2.7 on 2026-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('filter_type', models.CharField(choices=[('discount', 'بیشترین تخفیف'), ('new', 'جدیدترین\u200cها'), ('trending', 'محبوب\u200cترین\u200cها'), ('featured', 'ویژه'), ('category', 'دسته\u200cبندی'), ('brand', 'برند')], max_length=20, verbose_name='نوع فیلتر')),
                ('filter_value', models.CharField(blank=True, help_text='برای دسته\u200cبندی: slug دسته. برای برند: slug برند. برای تخفیف/جدید/محبوب: خالی', max_length=100, verbose_name='مقدار فیلتر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بخش صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای صفحه اصلی',
                'ordering': ['order'],
            },
        ),
    ]
