# Generated by Django 4.2.30 on 2026-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_homepagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='filter_type',
            field=models.CharField(choices=[('discount', 'بیشترین تخفیف'), ('new', 'جدیدترین\u200cها'), ('trending', 'محبوب\u200cترین\u200cها'), ('featured', 'ویژه'), ('category', 'دسته\u200cبندی'), ('brand', 'برند'), ('name', 'جستجوی نام')], max_length=20, verbose_name='نوع فیلتر'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='filter_value',
            field=models.CharField(blank=True, help_text='برای دسته\u200cبندی: slug دسته\u200cها با کاما (مثلاً men,women). برای برند: slug برند. برای تخفیف/جدید/محبوب: خالی', max_length=200, verbose_name='مقدار فیلتر'),
        ),
    ]
