# Generated by Django 4.2.7 on 2026-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_homepagesection_filter_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر')),
                ('image_url', models.URLField(blank=True, verbose_name='آدرس تصویر (جایگزین)')),
                ('link', models.CharField(blank=True, default='/products', max_length=300, verbose_name='لینک')),
                ('button_text', models.CharField(blank=True, default='خرید کنید', max_length=100, verbose_name='متن دکمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='styles/', verbose_name='تصویر')),
                ('image_url', models.URLField(blank=True, verbose_name='آدرس تصویر (جایگزین)')),
                ('link', models.CharField(blank=True, default='/products', max_length=300, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'استایل روز',
                'verbose_name_plural': 'استایل\u200cهای روز',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='filter_type',
            field=models.CharField(choices=[('discount', 'بیشترین تخفیف'), ('new', 'جدیدترین\u200cها'), ('trending', 'محبوب\u200cترین\u200cها'), ('bestseller', 'پرفروش\u200cترین\u200cها'), ('featured', 'ویژه'), ('category', 'دسته\u200cبندی'), ('brand', 'برند'), ('name', 'جستجوی نام')], max_length=20, verbose_name='نوع فیلتر'),
        ),
    ]
