# Generated by Django 4.2.7 on 2026-07-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_banner_stylelook_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('kids', 'بچگانه'), ('accessories', 'اکسسواری')], max_length=25, verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک'),
        ),
    ]
