# Generated by Django 4.2.7 on 2026-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeguide',
            options={'ordering': ['category', 'size'], 'verbose_name': 'راهنمای سایز', 'verbose_name_plural': 'راهنماهای سایز'},
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='foot_length',
            field=models.CharField(blank=True, max_length=20, verbose_name='طول پا'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='gender',
            field=models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('kids', 'بچگانه'), ('unisex', 'یونیسکس')], default='unisex', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='height_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر قد (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='height_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل قد (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='inseam',
            field=models.CharField(blank=True, max_length=20, verbose_name='فاق'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='measurement_guide',
            field=models.TextField(blank=True, verbose_name='راهنمای اندازه\u200cگیری'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='product_type',
            field=models.CharField(choices=[('clothing', 'لباس'), ('shoes', 'کفش'), ('underwear', 'لباس زیر'), ('accessories', 'اکسسواری')], default='clothing', max_length=15, verbose_name='نوع محصول'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='shoulder',
            field=models.CharField(blank=True, max_length=20, verbose_name='شانه'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='sleeve',
            field=models.CharField(blank=True, max_length=20, verbose_name='آستین'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='weight_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر وزن (کیلوگرم)'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='weight_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل وزن (کیلوگرم)'),
        ),
    ]
