# Generated by Django 3.2.4 on 2026-07-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت اصلی قبل از تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تمام\u200cشده برای محاسبه سود(ديده نميشود)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('بچگانه', 'بچگانه'), ('اکسسوری', 'اکسسوری')], max_length=25, verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش نهایی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='اگر خالی بگذارید، از SKU اولین واریانت استفاده می\u200cشود', max_length=50, null=True, unique=True, verbose_name='کد محصول پایه (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='gender',
            field=models.CharField(choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('بچگانه', 'بچگانه'), ('یونیسکس', 'یونیسکس')], default='unisex', max_length=10, verbose_name='جنسیت'),
        ),
    ]
