# Generated by Django 3.2.4 on 2026-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20260721_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='اگر خالی بگذارید، از SKU اولین واریانت استفاده می\u200cشود', max_length=50, null=True, verbose_name='کد محصول پایه (اختیاری)'),
        ),
    ]
