# Generated by Django 3.2.4 on 2026-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='این مقدار خودکار از مجموع موجودی واریانت\u200cها محاسبه می\u200cشود', verbose_name='موجودی کل (محاسبه خودکار)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تمام\u200cشده برای محاسبه سود(دیده نمیشود)'),
        ),
    ]
