# Generated by Django 3.2.4 on 2026-07-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20260721_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت مقایسه\u200cای'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تمام\u200cشده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('kids', 'بچگانه'), ('accessories', 'اکسسواری')], max_length=25, verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=50, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='gender',
            field=models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('kids', 'بچگانه'), ('unisex', 'یونیسکس')], default='unisex', max_length=10, verbose_name='جنسیت'),
        ),
    ]
