# Generated by Django 4.2.7 on 2026-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20260721_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت اصلی قبل از تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تمام\u200cشده (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('بچگانه', 'بچگانه'), ('اکسسوری', 'اکسسوری')], max_length=25, verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='کد محصول (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='موجودی کل'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تعدیل قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='کد واریانت (خالی = خودکار)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='موجودی واریانت (خالی = از محصول ارث\u200cبری)'),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='gender',
            field=models.CharField(choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('بچگانه', 'بچگانه'), ('unisex', 'یونیسکس')], default='unisex', max_length=10, verbose_name='جنسیت'),
        ),
    ]
