# Generated by Django 3.2.4 on 2026-07-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_compare_price_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylelook',
            name='link',
        ),
        migrations.AddField(
            model_name='stylelook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_looks', to='products.category', verbose_name='دسته\u200cبندی (برای لینک به محصولات این دسته)'),
        ),
        migrations.AddField(
            model_name='stylelook',
            name='gender',
            field=models.CharField(blank=True, choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('بچگانه', 'بچگانه'), ('unisex', 'یونیسکس')], default='unisex', max_length=10, verbose_name='جنسیت (برای لینک به محصولات با این جنسیت)'),
        ),
        migrations.AddField(
            model_name='stylelook',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_looks', to='products.product', verbose_name='محصول (برای لینک مستقیم)'),
        ),
        migrations.AddField(
            model_name='stylelook',
            name='products_link',
            field=models.BooleanField(default=False, verbose_name='لینک به محصولات'),
        ),
    ]
