# Generated by Django 3.2.4 on 2026-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20260721_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylelook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stylelook',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='stylelook',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stylelook',
            name='products_link',
        ),
        migrations.AddField(
            model_name='stylelook',
            name='link',
            field=models.CharField(blank=True, default='/products', max_length=300, verbose_name='لینک'),
        ),
    ]
