# Generated by Django 3.2.4 on 2026-07-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_stylelook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylelook',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='style_looks', to='products.Product', verbose_name='محصولات این استایل'),
        ),
    ]
