# Generated by Django 3.2.4 on 2026-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_stylelook_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylelook',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True, verbose_name='اسلاگ'),
        ),
    ]
