# Generated by Django 4.2.7 on 2026-08-05 10:17

from django.db import migrations, models


def convert_inherited_stock_to_null(apps, schema_editor):
    """
    Old semantics: variant.stock == 0 meant "inherit from product".
    New semantics: stock == None inherits, 0 means genuinely sold out.
    Convert existing zeros so behaviour is unchanged for old data.
    """
    ProductVariant = apps.get_model('products', 'ProductVariant')
    ProductVariant.objects.filter(stock=0).update(stock=None)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_stylelook_slug'),
    ]

    operations = [
        migrations.RunPython(convert_inherited_stock_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='موجودی واریانت (خالی = از محصول ارث\u200cبری)'),
        ),
    ]
