# Generated by Django 4.2.30 on 2026-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_stylelook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='موجودی واریانت (خالی = از محصول ارث\u200cبری)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان'),
        ),
    ]
