# Generated by Django 4.2.30 on 2026-08-14 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0023_imagevariantgeneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='کاور')),
                ('visibility', models.CharField(choices=[('private', 'خصوصی'), ('invite_only', 'فقط با دعوت')], default='private', max_length=20, verbose_name='حریم خصوصی')),
                ('invite_token_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('invite_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('invite_revoked', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_rooms', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'اتاق استایل',
                'verbose_name_plural': 'اتاق\u200cهای استایل',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleRoomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='افزوده\u200cشده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_room_items', to='products.product', verbose_name='محصول')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='style_rooms.styleroom', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'آیتم اتاق',
                'verbose_name_plural': 'آیتم\u200cهای اتاق',
            },
        ),
        migrations.CreateModel(
            name='StyleRoomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='نوع رویداد')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='style_rooms.styleroom', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'رویداد اتاق',
                'verbose_name_plural': 'رویدادهای اتاق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('member', 'عضو')], default='member', max_length=10, verbose_name='نقش')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='style_rooms.styleroom', verbose_name='اتاق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_room_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو اتاق',
                'verbose_name_plural': 'اعضای اتاق',
                'indexes': [models.Index(fields=['user', '-joined_at'], name='sr_member_user_joined_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='styleroommember',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='sr_member_room_user_unique'),
        ),
        migrations.AddIndex(
            model_name='styleroomitem',
            index=models.Index(fields=['room', '-created_at'], name='sr_item_room_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='styleroomitem',
            constraint=models.UniqueConstraint(fields=('room', 'product'), name='sr_item_room_product_unique'),
        ),
        migrations.AddIndex(
            model_name='styleroomevent',
            index=models.Index(fields=['room', '-created_at'], name='sr_event_room_created_idx'),
        ),
        migrations.AddIndex(
            model_name='styleroomevent',
            index=models.Index(fields=['actor', '-created_at'], name='sr_event_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='styleroom',
            index=models.Index(fields=['owner', '-updated_at'], name='sr_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='styleroom',
            index=models.Index(fields=['visibility'], name='sr_visibility_idx'),
        ),
    ]
