# Generated by Django 4.2.30 on 2026-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleroom',
            name='visibility',
            field=models.CharField(choices=[('private', 'خصوصی'), ('invite_only', 'فقط با دعوت')], default='private', help_text='خصوصی: فقط اعضای اتاق می\u200cتوانند آن را ببینند. فقط با دعوت: قصد مالک مبنی بر ورود فقط از طریق دعوتنامه است؛ در حال حاضر دسترسی همچنان فقط بر اساس عضویت است و با توکن معتبر می\u200cتوان در هر دو حالت پیوست.', max_length=20, verbose_name='حریم خصوصی'),
        ),
    ]
