# Generated by Django 5.2.17 on 2026-08-11 13:38

from django.conf import settings
from django.db import migrations, models


def normalize_cart_data(apps, schema_editor):
    Cart = apps.get_model('cart', 'Cart')
    CartItem = apps.get_model('cart', 'CartItem')

    def merge_cart(source, target):
        for item in CartItem.objects.filter(cart=source).order_by('pk'):
            existing = CartItem.objects.filter(
                cart=target,
                product_id=item.product_id,
                variant_id=item.variant_id,
            ).first()
            if existing:
                existing.quantity = max(existing.quantity, 0) + max(item.quantity, 0)
                if existing.quantity == 0:
                    existing.quantity = 1
                existing.save(update_fields=['quantity'])
                item.delete()
            else:
                item.cart = target
                item.quantity = max(item.quantity, 1)
                item.save(update_fields=['cart', 'quantity'])
        source.delete()

    user_ids = (
        Cart.objects.filter(user__isnull=False)
        .values_list('user_id', flat=True).distinct()
    )
    for user_id in user_ids:
        carts = list(Cart.objects.filter(user_id=user_id).order_by('pk'))
        for duplicate in carts[1:]:
            merge_cart(duplicate, carts[0])

    session_ids = (
        Cart.objects.filter(user__isnull=True, session_id__isnull=False)
        .values_list('session_id', flat=True).distinct()
    )
    for session_id in session_ids:
        carts = list(
            Cart.objects.filter(user__isnull=True, session_id=session_id).order_by('pk')
        )
        for duplicate in carts[1:]:
            merge_cart(duplicate, carts[0])

    CartItem.objects.filter(quantity__lte=0).update(quantity=1)
    duplicate_keys = (
        CartItem.objects.values('cart_id', 'product_id', 'variant_id')
        .annotate(count=models.Count('pk')).filter(count__gt=1)
    )
    for key in duplicate_keys:
        items = list(CartItem.objects.filter(
            cart_id=key['cart_id'],
            product_id=key['product_id'],
            variant_id=key['variant_id'],
        ).order_by('pk'))
        keeper = items[0]
        keeper.quantity = sum(max(item.quantity, 1) for item in items)
        keeper.save(update_fields=['quantity'])
        CartItem.objects.filter(pk__in=[item.pk for item in items[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_session_id_alter_cart_user_and_more'),
        ('products', '0020_productimage_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RunPython(normalize_cart_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False), ('user__isnull', True)), fields=('session_id',), name='unique_guest_cart_per_session'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('cart', 'product', 'variant'), name='unique_cart_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_item_quantity_positive'),
        ),
    ]
