"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static

# Load .env from project root (parent of backend/)
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY env var is not set!")

DEBUG = os.getenv('DEBUG', 'False') == 'True'
TRUST_PROXY_HEADERS = os.getenv('TRUST_PROXY_HEADERS', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:3002,http://127.0.0.1:3002'
).split(',')
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:3002,http://127.0.0.1:3002',
).split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-device-fingerprint',
    'x-request-id',
]

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.humanize',
    'corsheaders',
    'django_filters',
    'django_jalali',
    'django_q',
    'accounts',
    'products.apps.ProductsConfig',
    'cart',
    'orders',
    'blog',
    'pages',
    'payments',
    'dashboard',
    'chat',
    'style_rooms',
    'loyalty',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'shop.middleware.RequestLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shop.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# ---------------------------------------------------------------------------
# پیکربندی پنل ادمین (Unfold)
# مستندات: https://unfoldadmin.com/docs/
# ---------------------------------------------------------------------------
UNFOLD = {
    "SITE_TITLE": "فروشگاه مد — مدیریت",
    "SITE_HEADER": "LUXORA",
    "SITE_SUBHEADER": "میز کار مدیریت لاکچری",
    "SITE_SYMBOL": "checkroom",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_LANGUAGES": False,
    "THEME": None,
    "BORDER_RADIUS": "0.5rem",
    # Shell components use Unfold's global hook. Shared tokens and page-specific
    # styles are loaded later by templates to preserve the established cascade.
    "STYLES": [lambda request: static("admin/css/admin-layout.css")],
    "DASHBOARD_CALLBACK": "shop.admin_dashboard.dashboard_callback",
    "COLORS": {
        "font": {
            "subtle-light": "115 110 100",
            "default-light": "61 56 49",
            "important-light": "31 31 31",
            "subtle-dark": "166 162 154",
            "default-dark": "229 226 220",
            "important-dark": "250 248 244",
        },
        "primary": {
            "50": "250 249 246",
            "100": "242 238 230",
            "200": "229 222 208",
            "300": "210 199 179",
            "400": "181 166 141",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "30 64 175",
            "800": "30 58 138",
            "900": "30 52 102",
            "950": "23 37 84",
        },
        "base": {
            "50": "246 241 232",
            "100": "232 241 252",
            "200": "214 228 247",
            "300": "218 211 200",
            "400": "184 176 163",
            "500": "140 133 122",
            "600": "98 91 82",
            "700": "68 63 57",
            "800": "38 35 32",
            "900": "31 31 31",
            "950": "23 26 28",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {"title": "داشبورد", "separator": False, "items": [
                {"title": "خانه", "icon": "dashboard", "link": "/admin/"},
            ]},
            {
                "title": "فروش",
                "separator": True,
                "items": [
                    {"title": "سفارش‌ها", "icon": "shopping_bag", "link": "/admin/orders/order/"},
                    {"title": "آیتم‌های سفارش", "icon": "receipt_long", "link": "/admin/orders/orderitem/"},
                    {"title": "پرداخت‌ها", "icon": "payments", "link": "/admin/payments/payment/"},
                    {"title": "آدرس‌های ارسال", "icon": "local_shipping", "link": "/admin/orders/shippingaddress/"},
                    {"title": "کدهای تخفیف", "icon": "local_offer", "link": "/admin/orders/coupon/"},
                    {"title": "استفاده‌های کوپن", "icon": "confirmation_number", "link": "/admin/orders/couponusage/"},
                    {"title": "هدیه‌های خوش‌آمدگویی", "icon": "redeem", "link": "/admin/orders/welcomeclaim/"},
                    {"title": "سبدهای خرید", "icon": "shopping_cart", "link": "/admin/cart/cart/"},
                    {"title": "آیتم‌های سبد", "icon": "shopping_cart_checkout", "link": "/admin/cart/cartitem/"},
                ],
            },
            {
                "title": "کاتالوگ محصولات",
                "separator": True,
                "items": [
                    {"title": "محصولات", "icon": "inventory_2", "link": "/admin/products/product/"},
                    {"title": "تصاویر محصولات", "icon": "image", "link": "/admin/products/productimage/"},
                    {"title": "واریانت‌ها", "icon": "style", "link": "/admin/products/productvariant/"},
                    {"title": "دسته‌بندی‌ها", "icon": "category", "link": "/admin/products/category/"},
                    {"title": "برندها", "icon": "sell", "link": "/admin/products/brand/"},
                    {"title": "سایزها", "icon": "straighten", "link": "/admin/products/size/"},
                    {"title": "رنگ‌ها", "icon": "palette", "link": "/admin/products/color/"},
                    {"title": "جنس پارچه", "icon": "texture", "link": "/admin/products/fabric/"},
                    {"title": "راهنمای سایز", "icon": "apparel", "link": "/admin/products/sizeguide/"},
                    {"title": "نظرات محصولات", "icon": "reviews", "link": "/admin/products/review/"},
                    {"title": "علاقه‌مندی‌ها", "icon": "favorite", "link": "/admin/products/wishlist/"},
                    {"title": "بنرها", "icon": "panorama", "link": "/admin/products/banner/"},
                    {"title": "بخش‌های صفحه اصلی", "icon": "view_quilt", "link": "/admin/products/homepagesection/"},
                    {"title": "استایل‌های روز", "icon": "checkroom", "link": "/admin/products/stylelook/"},
                ],
            },
            {
                "title": "کاربران و امنیت",
                "separator": True,
                "items": [
                    {"title": "کاربران", "icon": "group", "link": "/admin/auth/user/"},
                    {"title": "گروه‌ها", "icon": "groups", "link": "/admin/auth/group/"},
                    {"title": "پروفایل‌ها", "icon": "badge", "link": "/admin/accounts/userprofile/"},
                    {"title": "تاریخچه ورود", "icon": "history", "link": "/admin/accounts/loginhistory/"},
                    {"title": "توکن‌ها", "icon": "key", "link": "/admin/authtoken/tokenproxy/"},
                ],
            },
            {
                "title": "محتوا",
                "separator": True,
                "items": [
                    {"title": "مقالات بلاگ", "icon": "article", "link": "/admin/blog/blogpost/"},
                    {"title": "دسته‌بندی‌های مجله", "icon": "topic", "link": "/admin/blog/blogcategory/"},
                    {"title": "سؤالات متداول", "icon": "quiz", "link": "/admin/pages/faq/"},
                    {"title": "نظرات مشتریان", "icon": "star_rate", "link": "/admin/pages/testimonial/"},
                    {"title": "رضایت مشتریان", "icon": "sentiment_satisfied", "link": "/admin/pages/customersatisfaction/"},
                    {"title": "ویژگی‌های سایت", "icon": "featured_play_list", "link": "/admin/pages/sitefeature/"},
                    {"title": "پیام‌های تماس", "icon": "mail", "link": "/admin/pages/contactmessage/"},
                    {"title": "اطلاعات تماس", "icon": "contact_phone", "link": "/admin/pages/contactinfo/"},
                    {"title": "تنظیمات سایت", "icon": "settings", "link": "/admin/pages/sitesettings/"},
                ],
            },
            {"title": "گفتگو و ارتباطات", "separator": True, "items": [
                {"title": "گفتگوها", "icon": "forum", "link": "/admin/chat/conversation/"},
                {"title": "پیام‌ها", "icon": "chat", "link": "/admin/chat/message/"},
                {"title": "اعلان‌های گفتگو", "icon": "notifications", "link": "/admin/chat/notification/"},
                {"title": "کاربران مسدود", "icon": "block", "link": "/admin/chat/block/"},
            ]},
            {"title": "مدیریت داخلی", "separator": True, "items": [
                {"title": "نوتیفیکیشن‌های مدیر", "icon": "notifications_active", "link": "/admin/dashboard/notification/"},
                {"title": "لاگ فعالیت", "icon": "manage_history", "link": "/admin/dashboard/activitylog/"},
                {"title": "وظایف", "icon": "task_alt", "link": "/admin/dashboard/todoitem/"},
                {"title": "یادداشت‌های مدیر", "icon": "sticky_note_2", "link": "/admin/dashboard/adminnote/"},
                {"title": "نقش‌های مدیر", "icon": "admin_panel_settings", "link": "/admin/dashboard/adminrole/"},
                {"title": "مجوزهای مدیر", "icon": "shield", "link": "/admin/dashboard/adminpermission/"},
                {"title": "مجوزهای نقش", "icon": "policy", "link": "/admin/dashboard/adminrolepermission/"},
            ]},
            {"title": "صف وظایف", "separator": True, "items": [
                {"title": "وظایف زمان‌بندی‌شده", "icon": "schedule", "link": "/admin/django_q/schedule/"},
                {"title": "وظایف در صف", "icon": "queue", "link": "/admin/django_q/ormq/"},
                {"title": "وظایف موفق", "icon": "check_circle", "link": "/admin/django_q/success/"},
                {"title": "وظایف ناموفق", "icon": "error", "link": "/admin/django_q/failure/"},
            ]},
        ],
    },
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_X_ACCEL_REDIRECT_PREFIX = os.getenv('MEDIA_X_ACCEL_REDIRECT_PREFIX', '')

# ─── Django REST Framework ─────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CookieTokenAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # ── Global Throttling ──
    'DEFAULT_THROTTLE_CLASSES': [
        'accounts.throttles.SecureAnonRateThrottle',
        'accounts.throttles.SecureUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/hour',
        'user': '2000/hour',
        # Scoped rates for sensitive endpoints
        'login': '5/min',
        'register': '5/min',
        'send_otp': '3/min',
        'verify_otp': '5/min',
        'forgot_password': '3/min',
        'reset_password': '5/min',
        'payment_init': '10/min',
        'payment_verify': '5/min',
        'payment_webhook': '60/min',
        'coupon_apply': '20/min',
        'chat_send': '60/min',
        'room_write': '60/min',
        'room_invite': '10/hour',
    },

    # ── Exception handler for consistent throttle/lockout responses ──
    'EXCEPTION_HANDLER': 'shop.exceptions.custom_exception_handler',
}

# ─── Default primary key field type ────────────────────────

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Cache Configuration ───────────────────────────────────
# LocMemCache is used by default and is fine for development and
# single-process deployments.
#
# PRODUCTION (multi-worker, e.g. gunicorn with several workers):
# the API throttles (accounts, chat, style_rooms, payments, …) and the
# session/OTP stores are backed by the default cache. LocMemCache is
# per-process, so each worker would get its own throttle budget and the
# configured rates would be effectively multiplied by the worker count.
# A shared backend is REQUIRED for correct distributed limiting:
#
#   REDIS_URL=redis://<host>:6379/0
#
# must be provided by the environment; nothing here hardcodes a URL or
# credentials. When REDIS_URL is empty we intentionally keep LocMemCache
# as the safe development fallback — Redis is never assumed to exist.

REDIS_URL = os.getenv('REDIS_URL', '')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'shop',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'shop-security',
        }
    }

# ─── Security Settings ─────────────────────────────────────

# HSTS (enable when HTTPS is confirmed)
# Set SECURE_HSTS_SECONDS=31536000 in .env for production
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False') == 'True'
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', str(not DEBUG)) == 'True'
if TRUST_PROXY_HEADERS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = False  # This non-secret token is echoed by Axios.
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'

# Additional security headers (handled by middleware, but also set here for Django built-ins)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = False  # Disabled — CSP replaces it
X_FRAME_OPTIONS = 'DENY'

# ─── Logging Configuration ─────────────────────────────────
# Production-grade logging with rotating file handlers,
# separate loggers per domain, and structured formatting.

LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # ── Formatters ────────────────────────────────────────
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'json': {
            '()': 'shop.observability.JsonFormatter',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'security': {
            'format': '{asctime} [SECURITY] {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    # ── Filters ───────────────────────────────────────────
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    # ── Handlers ──────────────────────────────────────────
    'handlers': {
        # Console (always active — for development and containerized deploys)
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'console_simple': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },

        # ── Rotating file handlers ────────────────────────
        # All application logs (info+)
        'application_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'application.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },

        # Errors only (warning+, across all loggers)
        'errors_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'errors.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 15,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },

        # Security events (lockouts, OTP abuse, rate limits, suspicious activity)
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'security.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 20,
            'formatter': 'security',
            'encoding': 'utf-8',
        },

        # Payment events (initiation, verification, gateway responses, failures)
        'payment_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'payment.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 15,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },

        # Null handler to prevent "No handler" warnings
        'null': {
            'class': 'logging.NullHandler',
        },
    },

    # ── Loggers ───────────────────────────────────────────
    'loggers': {
        # Django core — catches middleware/startup messages
        'django': {
            'handlers': ['console', 'application_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Request/response lifecycle — 4xx/5xx
        'django.request': {
            'handlers': ['console', 'application_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Security middleware, CSRF, permission denied
        'django.security': {
            'handlers': ['console', 'security_file', 'errors_file'],
            'level': 'WARNING',
            'propagate': False,
        },

        # Database queries (only in DEBUG)
        'django.db.backends': {
            'handlers': ['null'] if not DEBUG else ['console'],
            'level': 'WARNING',
            'propagate': False,
        },

        # ── Application loggers ──────────────────────────

        # General application events
        'application': {
            'handlers': ['console', 'application_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Authentication: login, register, OTP, password reset
        'authentication': {
            'handlers': ['console', 'application_file', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Payment gateway interactions
        'payment': {
            'handlers': ['console', 'payment_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Order lifecycle events
        'orders': {
            'handlers': ['console', 'application_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Inventory management
        'inventory': {
            'handlers': ['console', 'application_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Security events (lockouts, abuse, suspicious requests)
        'security': {
            'handlers': ['console', 'security_file', 'errors_file'],
            'level': 'WARNING',
            'propagate': False,
        },

        # API performance and usage
        'api': {
            'handlers': ['console', 'application_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Email service (send status, errors)
        'email': {
            'handlers': ['console', 'application_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # Catch-all for any third-party or unhandled loggers
        '': {
            'handlers': ['console', 'errors_file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },

    # ── Root logger ───────────────────────────────────────
    'root': {
        'handlers': ['console', 'errors_file'],
        'level': 'WARNING',
    },
}

# ─── Email Configuration (Gmail SMTP) ──────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SMS_OTP_PROVIDER = os.getenv('SMS_OTP_PROVIDER', '')

# hCaptcha by default; reCAPTCHA can be used by overriding CAPTCHA_VERIFY_URL.
CAPTCHA_SECRET_KEY = os.getenv('CAPTCHA_SECRET_KEY', '')
CAPTCHA_VERIFY_URL = os.getenv(
    'CAPTCHA_VERIFY_URL',
    'https://hcaptcha.com/siteverify',
)

AUTH_TOKEN_COOKIE_NAME = os.getenv('AUTH_TOKEN_COOKIE_NAME', 'shop_auth')
AUTH_TOKEN_COOKIE_MAX_AGE = int(os.getenv('AUTH_TOKEN_COOKIE_MAX_AGE', str(14 * 24 * 3600)))
AUTH_TOKEN_COOKIE_SECURE = not DEBUG
AUTH_TOKEN_COOKIE_SAMESITE = os.getenv('AUTH_TOKEN_COOKIE_SAMESITE', 'Lax')

Q_CLUSTER = {
    'name': 'shop',
    'workers': int(os.getenv('Q_WORKERS', '2')),
    'timeout': int(os.getenv('Q_TIMEOUT', '120')),
    'retry': int(os.getenv('Q_RETRY', '180')),
    'queue_limit': int(os.getenv('Q_QUEUE_LIMIT', '50')),
    'bulk': 10,
    'orm': 'default',
    'save_limit': int(os.getenv('Q_SAVE_LIMIT', '250')),
}
EMAIL_MAX_ATTEMPTS = int(os.getenv('EMAIL_MAX_ATTEMPTS', '3'))
EMAIL_RETRY_BASE_SECONDS = int(os.getenv('EMAIL_RETRY_BASE_SECONDS', '60'))
EMAIL_RETRY_MAX_SECONDS = int(os.getenv('EMAIL_RETRY_MAX_SECONDS', '900'))

# ─── Zarinpal Payment Gateway ──────────────────────────────
ZARINPAL_MERCHANT_ID = os.getenv('ZARINPAL_MERCHANT_ID', '')
ZARINPAL_SANDBOX = os.getenv('ZARINPAL_SANDBOX', 'True') == 'True'
ZARINPAL_CALLBACK_URL = os.getenv(
    'ZARINPAL_CALLBACK_URL',
    'http://localhost:8000/api/payments/verify/'
)

# ─── Sentry Configuration ──────────────────────────────────
# Set SENTRY_DSN in .env to enable error tracking in production.
# Install: pip install sentry-sdk
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1'))
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT', 'production')

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.logging import LoggingIntegration

        sentry_logging = LoggingIntegration(
            level=logging.WARNING,        # Send warnings and above to Sentry
            event_level=logging.ERROR,    # Create Sentry events for errors+
        )

        from shop.observability import sentry_before_send, sentry_before_breadcrumb

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                sentry_logging,
            ],
            environment=SENTRY_ENVIRONMENT,
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            send_default_pii=False,
            before_send=sentry_before_send,
            before_breadcrumb=sentry_before_breadcrumb,
            enable_tracing=True,
            release=os.getenv('SENTRY_RELEASE', 'shop@latest'),
        )
        import logging as _logging
        _logging.getLogger('shop').info(
            'Sentry initialized: environment=%s traces_sample_rate=%.2f',
            SENTRY_ENVIRONMENT, SENTRY_TRACES_SAMPLE_RATE,
        )
    except ImportError:
        import logging as _logging
        _logging.getLogger('shop').warning(
            'sentry-sdk not installed. Install with: pip install sentry-sdk'
        )
    except Exception as e:
        import logging as _logging
        _logging.getLogger('shop').warning('Sentry initialization failed: %s', e)
