# Generated by Django 4.2.7 on 2026-07-27 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مجوز')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('category', models.CharField(choices=[('products', 'محصولات'), ('orders', 'سفارشات'), ('customers', 'مشتریان'), ('reports', 'گزارشات'), ('settings', 'تنظیمات'), ('users', 'کاربران')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مجوز ادمین',
                'verbose_name_plural': 'مجوزهای ادمین',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نقش')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نقش ادمین',
                'verbose_name_plural': 'نقش\u200cهای ادمین',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('target_type', models.CharField(choices=[('order', 'سفارش'), ('product', 'محصول'), ('customer', 'مشتری'), ('general', 'عمومی')], default='general', max_length=20, verbose_name='نوع هدف')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه هدف')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='سنجاق شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'یادداشت ادمین',
                'verbose_name_plural': 'یادداشت\u200cهای ادمین',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='dashboard.adminpermission', verbose_name='مجوز')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='dashboard.adminrole', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'مجوز نقش',
                'verbose_name_plural': 'مجوزهای نقش',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
