# Generated by Django 4.2.30 on 2026-08-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر (آپلود)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, verbose_name='آدرس تصویر (جایگزین)'),
        ),
    ]
