# Generated by Django 5.2.17 on 2026-08-12 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_image_upload_alter_blogpost_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', '-published_at'], name='blog_published_date_idx'),
        ),
    ]
