# Generated by Django 4.2.30 on 2026-08-14 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_orderitem_inventory_source_snapshot'),
        ('products', '0023_imagevariantgeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_points', models.PositiveIntegerField(default=0)),
                ('total_earned', models.PositiveIntegerField(default=0)),
                ('total_redeemed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty account',
                'verbose_name_plural': 'Loyalty accounts',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty event type',
                'verbose_name_plural': 'Loyalty event types',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='loyalty.loyaltyeventtype')),
            ],
            options={
                'verbose_name': 'Loyalty rule',
                'verbose_name_plural': 'Loyalty rules',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRewardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('minimum_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tiers', to='loyalty.loyaltyrule')),
            ],
            options={
                'verbose_name': 'Purchase reward tier',
                'verbose_name_plural': 'Purchase reward tiers',
                'ordering': ['-priority', 'minimum_order_total', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('reward', 'Reward'), ('redemption', 'Redemption'), ('reversal', 'Reversal'), ('adjustment', 'Manual adjustment')], default='reward', max_length=16)),
                ('points_delta', models.IntegerField()),
                ('idempotency_key', models.CharField(max_length=191, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loyalty.loyaltyeventtype')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='products.product')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_loyalty_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='loyalty.loyaltytransaction')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty.loyaltyrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty transaction',
                'verbose_name_plural': 'Loyalty transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaserewardtier',
            constraint=models.CheckConstraint(check=models.Q(('maximum_order_total__isnull', True), ('maximum_order_total__gte', models.F('minimum_order_total')), _connector='OR'), name='loyalty_tier_valid_total_range'),
        ),
        migrations.AddConstraint(
            model_name='purchaserewardtier',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='loyalty_tier_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='purchaserewardtier',
            constraint=models.UniqueConstraint(fields=('rule', 'priority'), name='loyalty_tier_rule_priority_unique'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['user', '-created_at'], name='loyalty_tx_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['event_type', '-created_at'], name='loyalty_tx_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['order'], name='loyalty_tx_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.CheckConstraint(check=models.Q(('points_delta', 0), _negated=True), name='loyalty_tx_nonzero_delta'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyrule',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='loyalty_rule_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.CheckConstraint(check=models.Q(('available_points__gte', 0)), name='loyalty_account_available_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.CheckConstraint(check=models.Q(('total_earned__gte', 0)), name='loyalty_account_earned_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.CheckConstraint(check=models.Q(('total_redeemed__gte', 0)), name='loyalty_account_redeemed_nonnegative'),
        ),
    ]
