# Generated by Django 4.2.7 on 2026-07-21 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_orderitem_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد احراز هویت')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره مرجع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'بازپرداخت شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('card_pan', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='کارمزد')),
                ('error_code', models.IntegerField(default=0, verbose_name='کد خطا')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
