# Generated by Django 4.2.30 on 2026-08-17 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_single_open_conversation_per_customer_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAgentPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('claim', 'Claim'), ('assign', 'Assign'), ('reassign', 'Reassign'), ('auto', 'Auto'), ('requeue', 'Requeue')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='supportconversation',
            name='support_queue_idx',
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['department', 'status', 'created_at'], name='support_queue_created_idx'),
        ),
        migrations.AddField(
            model_name='supportassignment',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportassignment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportassignment',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='support.supportconversation'),
        ),
        migrations.AddField(
            model_name='supportassignment',
            name='previous_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportagentpresence',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_presence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supportassignment',
            index=models.Index(fields=['conversation', '-created_at'], name='support_assign_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='supportassignment',
            index=models.Index(fields=['agent', '-created_at'], name='support_assign_agent_idx'),
        ),
        migrations.AddIndex(
            model_name='supportagentpresence',
            index=models.Index(fields=['status', '-last_seen_at'], name='support_presence_seen_idx'),
        ),
    ]
