# Generated by Django 4.2.30 on 2026-08-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_imagevariantgeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Product view'), ('search', 'Search'), ('wishlist_add', 'Wishlist add'), ('wishlist_remove', 'Wishlist remove'), ('cart_add', 'Cart add'), ('cart_remove', 'Cart remove'), ('purchase', 'Purchase'), ('review', 'Review'), ('product_share', 'Product share')], max_length=32, unique=True)),
                ('weight', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Product view'), ('search', 'Search'), ('wishlist_add', 'Wishlist add'), ('wishlist_remove', 'Wishlist remove'), ('cart_add', 'Cart add'), ('cart_remove', 'Cart remove'), ('purchase', 'Purchase'), ('review', 'Review'), ('product_share', 'Product share')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=191, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalization_events', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalization_events', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalization_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('gender', 'Gender / main category'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('brand', 'Brand'), ('fabric', 'Fabric'), ('color', 'Color')], max_length=32)),
                ('value_key', models.CharField(max_length=191)),
                ('value_label', models.CharField(blank=True, max_length=191)),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalization_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'dimension', 'value_key'],
                'indexes': [models.Index(fields=['user', 'dimension', 'value_key'], name='pe_pref_user_dim_value_idx'), models.Index(fields=['user', '-score'], name='pe_pref_user_score_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.UniqueConstraint(fields=('user', 'dimension', 'value_key'), name='pe_preference_user_dimension_value_unique'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['user', '-occurred_at'], name='pe_event_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['user', 'event_type', '-occurred_at'], name='pe_event_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['product', '-occurred_at'], name='pe_event_product_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='behaviorevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'event_type', 'idempotency_key'), name='pe_event_user_type_key_unique'),
        ),
    ]
