# Generated by Django 4.2.30 on 2026-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDecayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Product view'), ('search', 'Search'), ('wishlist_add', 'Wishlist add'), ('wishlist_remove', 'Wishlist remove'), ('cart_add', 'Cart add'), ('cart_remove', 'Cart remove'), ('purchase', 'Purchase'), ('review', 'Review'), ('product_share', 'Product share')], max_length=32, unique=True)),
                ('half_life_days', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_type'],
            },
        ),
    ]
